name: bloc_test
description: A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
version: 9.1.0
repository: https://github.com/felangel/bloc/tree/master/packages/bloc_test
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/#/gettingstarted

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  diff_match_patch: ^0.4.1
  meta: ^1.3.0
  mocktail:
    git:
      url: git@github.com:tyemykuga/mocktail.git
      ref: main
      path: packages/mocktail
  test: ^1.22.1

dev_dependencies:
  rxdart: ^0.27.2
