name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 8.1.0
repository: https://github.com/felangel/bloc/tree/master/packages/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mocktail:
    git:
      url: git@github.com:tyemykuga/mocktail.git
      ref: main
      path: packages/mocktail
  stream_transform: ^2.0.0
  test: ^1.22.1
